In [88]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go

In [89]:
dados = pd.read_csv('https://data.insideairbnb.com/united-states/ma/boston/2024-06-22/visualisations/listings.csv')
dados

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,3781,HARBORSIDE-Walk to subway,4804,Frank,NaN,East Boston,42.364130,-71.029910,Entire home/apt,125.0,29,25,2023-12-11,0.23,1,317,1,NaN
1,5506,** Fort Hill Inn Private! Minutes to center!**,8229,Terry,NaN,Roxbury,42.328440,-71.095810,Entire home/apt,139.0,3,123,2024-04-24,0.66,10,112,5,STR-490093
2,6695,"Fort Hill Inn *Sunny* 1 bedroom, condo duplex",8229,Terry,NaN,Roxbury,42.328020,-71.093870,Entire home/apt,179.0,3,128,2024-04-16,0.71,10,79,4,STR-491702
3,8789,Curved Glass Studio/1bd facing Park,26988,Anne,NaN,Beacon Hill,42.358670,-71.063070,Entire home/apt,92.0,91,29,2024-05-15,0.24,8,101,3,NaN
4,10811,"Back Bay Apt Studio-3 blocks to Pru center & ""T""",38997,Michelle,NaN,Back Bay,42.351730,-71.086850,Entire home/apt,130.0,91,9,2019-07-22,0.09,13,364,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4320,1181310640039457019,"The Chester: Modern Luxury, Historic Charm",43613912,Drew,NaN,Roxbury,42.339042,-71.080357,Entire home/apt,169.0,2,0,NaN,NaN,10,32,0,STR-565048
4321,1181310920532325010,"The Chester: Urban Luxury, Modern Design",43613912,Drew,NaN,Roxbury,42.339042,-71.080357,Entire home/apt,217.0,2,0,NaN,NaN,10,159,0,STR-565049
4322,1181311064422167794,"The Chester: Modern, Cool, Heart Of South End",43613912,Drew,NaN,Roxbury,42.339042,-71.080357,Entire home/apt,213.0,2,0,NaN,NaN,10,158,0,STR-565053
4323,1182535715185750063,Luxury one bedroom,28929296,Seif,NaN,South End,42.345838,-71.064972,Entire home/apt,250.0,1,0,NaN,NaN,6,46,0,STR-359412
4324,1183366210963015944,"Large 4 Bedroom apartments, 2RD FL/Brighton",426546484,Mike,NaN,Brighton,42.343210,-71.146980,Entire home/apt,350.0,1,0,NaN,NaN,1,365,0,STR-460830

In [90]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4325 entries, 0 to 4324
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              4325 non-null   int64
 1   name                            4325 non-null   object
 2   host_id                         4325 non-null   int64
 3   host_name                       4325 non-null   object
 4   neighbourhood_group             0 non-null      float64
 5   neighbourhood                   4325 non-null   object
 6   latitude                        4325 non-null   float64
 7   longitude                       4325 non-null   float64
 8   room_type                       4325 non-null   object
 9   price                           3543 non-null   float64
 10  minimum_nights                  4325 non-null   int64
 11  number_of_reviews               4325 non-null   int64
 12  last_review                     3326 non-null   object
 13  reviews_per_month               3326 non-null   float64
 14  calculated_host_listings_count  4325 non-null   int64
 15  availability_365                4325 non-null   int64
 16  number_of_reviews_ltm           4325 non-null   int64
 17  license                         2792 non-null   object
dtypes: float64(5), int64(7), object(6)
memory usage: 608.3+ KB

In [91]:
dados.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license'],
      dtype='object')

In [92]:
dados = dados.drop('neighbourhood_group', axis=1)
dados = dados.dropna()
dados

,id,name,host_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
1,5506,** Fort Hill Inn Private! Minutes to center!**,8229,Terry,Roxbury,42.328440,-71.095810,Entire home/apt,139.0,3,123,2024-04-24,0.66,10,112,5,STR-490093
2,6695,"Fort Hill Inn *Sunny* 1 bedroom, condo duplex",8229,Terry,Roxbury,42.328020,-71.093870,Entire home/apt,179.0,3,128,2024-04-16,0.71,10,79,4,STR-491702
9,40601,Private room & bath - Jamaica Plain,174986,Robert,Jamaica Plain,42.313470,-71.110820,Private room,100.0,29,99,2024-05-05,0.59,1,113,5,STR-551851
10,45987,Garden Studio,205107,Atef,Charlestown,42.374240,-71.060810,Entire home/apt,100.0,29,139,2024-06-18,0.83,1,55,3,STR-409822
11,47521,"Private Room, shared bath in Victorian House/ 1",119019,Hermina,Dorchester,42.298710,-71.059540,Private room,100.0,1,333,2023-11-05,1.98,8,348,1,STR-492781
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4286,1175344947100869764,Huge Studio in Downtown Boston 1409,212359760,Evonify,Downtown,42.351200,-71.063440,Entire home/apt,195.0,1,3,2024-06-17,3.00,62,297,3,Exempt: This listing is a unit that has contra...
4292,1176861035408746030,Cozy Boston studio with separate bedroom,416027128,R Living,Brighton,42.346146,-71.144161,Entire home/apt,167.0,29,2,2024-06-20,2.00,20,256,2,Exempt: This listing is a unit that has contra...
4293,1177103248225483462,Stylish studio with room divider near downtown,416027128,R Living,Brighton,42.348337,-71.144936,Entire home/apt,132.0,29,1,2024-06-17,1.00,20,267,1,Exempt: This listing is a unit that has contra...
4296,1177619455488589855,Luxury South End 1 Bedroom,62211530,Marina,South End,42.344290,-71.063190,Entire home/apt,198.0,1,1,2024-06-19,1.00,7,255,1,STr-008687
4301,1178933965841931292,"Best Location, 1 bedroom Apartment, Beacon Hill",351555234,Airbnb,Beacon Hill,42.358910,-71.065440,Entire home/apt,975.0,1,1,2024-06-16,1.00,2,84,1,str-543851

In [93]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2214 entries, 1 to 4301
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              2214 non-null   int64
 1   name                            2214 non-null   object
 2   host_id                         2214 non-null   int64
 3   host_name                       2214 non-null   object
 4   neighbourhood                   2214 non-null   object
 5   latitude                        2214 non-null   float64
 6   longitude                       2214 non-null   float64
 7   room_type                       2214 non-null   object
 8   price                           2214 non-null   float64
 9   minimum_nights                  2214 non-null   int64
 10  number_of_reviews               2214 non-null   int64
 11  last_review                     2214 non-null   object
 12  reviews_per_month               2214 non-null   float64
 13  calculated_host_listings_count  2214 non-null   int64
 14  availability_365                2214 non-null   int64
 15  number_of_reviews_ltm           2214 non-null   int64
 16  license                         2214 non-null   object
dtypes: float64(4), int64(7), object(6)
memory usage: 311.3+ KB

In [94]:
def geraHistograma(titulo,nomeEixoX,dadosEixo,cor,altura,largura,numeroBarras):
  if numeroBarras=="":
    numeroBarras=None
  # criaÃ§Ã£o de uma figure para montar o histograma
  fig = go.Figure()
  # gera o histograma
  fig.add_trace(go.Histogram(x=dadosEixo,marker_line=dict(width=1, color='black'),marker_color=cor,nbinsx=numeroBarras))
  #define layout do grÃ¡fico
  fig.update_layout(
      height=altura,
      width=largura,
      title_text=titulo,
      title_font_size=20,
      xaxis_title=nomeEixoX
      )
  fig.show()
  return

In [97]:
geraHistograma(
    titulo="Histograma de Price",
    nomeEixoX="Price",
    dadosEixo=dados['price'],
    cor="blue",
    altura=400,
    largura=800,
    numeroBarras="")

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed